### ISSUE TITLE
no edge_attr

### ISSUE THREAD

**Issue by pw-pw** [willyfh/graph-transformer#2]
Thank you very much for your code. I have a question : I only have node features and  adjacency matrix. How should I use this module?

**Comment by willyfh** [comment]
Thank you for raising this issue. I have released new updates in **v0.2.1**. In the latest update, if your graph does not have edge features, you can set `edge_dim` and `edges` (in the forward pass) to `None`. 

**Example:**

``` python
import torch
from graph_transformer import GraphTransformerModel

model = GraphTransformerModel(
        node_dim = 512,
        edge_dim = None,
        num_blocks = 3, 
        num_heads = 8,
        last_average=True, 
        model_dim=None
)

nodes = torch.randn(1, 128, 512)
edges = torch.randn(1, 128, 128, 512)
adjacency = torch.ones(1, 128, 128)

nodes = model(nodes, None, adjacency)
```
